runtime: nodejs18
env: standard
instance_class: F1

handlers:
  - url: /assets
    static_dir: dist/assets
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  VITE_SUPABASE_URL: "https://your-project.supabase.co"
  VITE_SUPABASE_ANON_KEY: "your-anon-key-here"
  VITE_PAYSTACK_PUBLIC_KEY: "pk_test_your-key"
  VITE_STRIPE_PUBLISHABLE_KEY: "pk_test_your-key"
  VITE_SENDGRID_API_KEY: "your-sendgrid-key"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
